[package]
name = "ral"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
cpal = "0.14.2"
phf = { version = "0.11", features = ["macros"] }
rand = "0.8.5"